version: '3.8'

services:
  bug-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    container_name: bug-tracker
    depends_on:
      - cass-1
    environment:
      - SPRING_DATASOURCE_URL=cassandra://cassandra:9042
    networks:
      - cassandra

  cass-1:
    image: cassandra:latest
    container_name: cass-1
    hostname: cass-1
    environment:
      - CASSANDRA_CLUSTER_NAME=cass-cluster
    ports:
      - '9042:9042'
    networks:
      - cassandra

networks:
  cassandra:
    driver: bridge